spring.application.name=devops-demo

server.port=8080

app.version=1.0.0

management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.health.show-details=always

management.metrics.tags.application=${spring.application.name}